// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fPvl-XHzcqtM7qrnOIKloqd8xw2mj9A',
    appId: '1:448752377065:web:411c0877332c49c195a478',
    messagingSenderId: '448752377065',
    projectId: 'resturanttest-54e2e',
    authDomain: 'resturanttest-54e2e.firebaseapp.com',
    storageBucket: 'resturanttest-54e2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gKDXuWT3vMgaJ4kxj3Ku5-oEuI7jDEc',
    appId: '1:448752377065:android:ad2711d1f391044795a478',
    messagingSenderId: '448752377065',
    projectId: 'resturanttest-54e2e',
    storageBucket: 'resturanttest-54e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZaYAQnXn3g7OsGUat7JVa7gDFVHHYvs',
    appId: '1:448752377065:ios:3087a08e51b05c4795a478',
    messagingSenderId: '448752377065',
    projectId: 'resturanttest-54e2e',
    storageBucket: 'resturanttest-54e2e.appspot.com',
    iosBundleId: 'com.example.yemenhistory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZaYAQnXn3g7OsGUat7JVa7gDFVHHYvs',
    appId: '1:448752377065:ios:3087a08e51b05c4795a478',
    messagingSenderId: '448752377065',
    projectId: 'resturanttest-54e2e',
    storageBucket: 'resturanttest-54e2e.appspot.com',
    iosBundleId: 'com.example.yemenhistory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_fPvl-XHzcqtM7qrnOIKloqd8xw2mj9A',
    appId: '1:448752377065:web:411c0877332c49c195a478',
    messagingSenderId: '448752377065',
    projectId: 'resturanttest-54e2e',
    authDomain: 'resturanttest-54e2e.firebaseapp.com',
    storageBucket: 'resturanttest-54e2e.appspot.com',
  );

}