// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5TJw9DrBe1gUwD8yw32aSYWbYiIHTZk',
    appId: '1:28631560840:web:9a6e3b87c133f05ab9a53d',
    messagingSenderId: '28631560840',
    projectId: 'yemen-history-15c00',
    authDomain: 'yemen-history-15c00.firebaseapp.com',
    storageBucket: 'yemen-history-15c00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdYuCSMoKbBmBvTwj2ie7mzMmVo0L_Is',
    appId: '1:28631560840:android:e5ae2239447dc129b9a53d',
    messagingSenderId: '28631560840',
    projectId: 'yemen-history-15c00',
    storageBucket: 'yemen-history-15c00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwaR3UYjDJUWXu9g2wKCtP5HmrjxvdfQ',
    appId: '1:28631560840:ios:7de2c4e38c1590ddb9a53d',
    messagingSenderId: '28631560840',
    projectId: 'yemen-history-15c00',
    storageBucket: 'yemen-history-15c00.firebasestorage.app',
    iosBundleId: 'com.example.yemenhistory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwaR3UYjDJUWXu9g2wKCtP5HmrjxvdfQ',
    appId: '1:28631560840:ios:7de2c4e38c1590ddb9a53d',
    messagingSenderId: '28631560840',
    projectId: 'yemen-history-15c00',
    storageBucket: 'yemen-history-15c00.firebasestorage.app',
    iosBundleId: 'com.example.yemenhistory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt5TJw9DrBe1gUwD8yw32aSYWbYiIHTZk',
    appId: '1:28631560840:web:e7f16067d309b0dab9a53d',
    messagingSenderId: '28631560840',
    projectId: 'yemen-history-15c00',
    authDomain: 'yemen-history-15c00.firebaseapp.com',
    storageBucket: 'yemen-history-15c00.firebasestorage.app',
  );
}
